--<ScriptOptions statementTerminator=";"/>

CREATE TABLE PLAYER (
		USERNAME VARCHAR(50) NOT NULL,
		BALANCE_VERSION INTEGER NOT NULL,
		BALANCE DECIMAL(12 , 2) NOT NULL
	);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10499_10500 ON PLAYER (USERNAME ASC);

ALTER TABLE PLAYER ADD CONSTRAINT SYS_PK_10499 PRIMARY KEY (USERNAME);

INSERT INTO PUBLIC.PLAYER ( USERNAME, BALANCE_VERSION, BALANCE )VALUES ('PLAYER_A',1,25.00);
INSERT INTO PUBLIC.PLAYER ( USERNAME, BALANCE_VERSION, BALANCE )VALUES ('PLAYER_B',1,100.00);
INSERT INTO PUBLIC.PLAYER ( USERNAME, BALANCE_VERSION, BALANCE )VALUES ('PLAYER_C',1,150.50);